config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   root  'blogs#index'
   resources :blogs   do#tweets_controllerに対してのresourcesメソッド
   resources :comments, only: [:create]
  end
  resources :users, only: [:show]  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many   :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :blogs
         has_many  :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters ,if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 before_action :move_to_index, except: [:index,:show]
  def index
     @blogs = Blog.includes(:user).order("created_at DESC").page(params[:page]).per(5)
   end
   def new
   end
   def create
    Blog.create(image: blog_params[:image],text: blog_params[:text],user_id: current_user.id)
  end
  def destroy
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.destroy
    end
  end
  def edit
    @blog = Blog.find(params[:id])
  end
  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end
  def show
    @blog = Blog.find(params[:id])
    @comments = @blog.comments.includes(:user)
  end
   private
  def blog_params
    params.permit(:image, :text)
  end
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
     @comment = Comment.create(text: params[:text],blog_id: params[:blog_id],user_id: current_user.id)
     redirect_to "/blogs/#{@comment.blog.id}"
  end
  private
  def comment_params
    params.permit(:text, :tweet_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
     user = User.find(params[:id])
   @nickname = user.nickname
    @blogs =  user.blogs.page(params[:page]).per(5).order("created_at DESC")
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<div class="body-content" style="background-image: url(<%= blog.image %>);">
          <ul>
            <li>
              <%= link_to 'SHOW', blog_path(blog.id), method: :get %>
            </li>
            <%if user_signed_in? && current_user.id== blog.user_id %>
             <li>
              <%= link_to 'EDIT', "/blogs/#{blog.id}/edit", method: :get %>
             </li>
               <li>
              <%= link_to'DESTROY',"/blogs/#{blog.id}",method: :delete %>
               </li>
            <% end %>
          </ul>
      <div class="tweet"><%= simple_format(blog.text) %></div>
      <span class="name">
        <a href="/users/<%= blog.user_id %>">
          <span>投稿者   </span><%= blog.user.nickname %>
        </a>
      </span>
    </div>

app/views/blogs/create.html.erb
<div class="body">
<div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/blogs">投稿一覧へ戻る</a>
  </div>
  </div>

app/views/blogs/destroy.html.erb
<div class="body">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="body">
  <div class="tweet-container"></div>
  <%= form_tag("/blogs/#{@blog.id}",method: :patch) do %>
  <h3>
    編集する
  </h3>
  <div class="tweet-comment">
  <input type="text" name="image" value="<%=@blog.image %>" placeholder="Image Url" autofocus="true">
  <textarea name="text" placeholder="text" rows="10" cols="30"><%= @blog.text %></textarea>
  <input type="submit" value="SENT">
  </div>
  <% end %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="body">
<% @blogs.each do |blog| %>
<div class="tweet">
<%= render partial: "blogs/blog", locals: { blog: blog } %>
<% end %>
</div>
   <%= paginate(@blogs) %>
   </div>

app/views/blogs/new.html.erb
<div class="body">
  <div class="tweet-container">
  <%= form_tag('/blogs', method: :post) do %>
    <h3>
      投稿する
    </h3>
    <div class="tweet-comment">
    <input type="text" name="image" placeholder="Image Url">
    <textarea name="text" placeholder="text" rows="10" cols="30"></textarea>
    <input type="submit" value="SEND">
    </div>
  <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="body">
  <div  class="body-content" style="background-image: url(<%= @blog.image %>);">
    <% if user_signed_in? && current_user.id == @blog.user_id %>
      <ul >
        <li>
          <%= link_to 'EDIT' ,"/blogs/#{@blog.id}/edit", method: :get %>
        </li>
        <li>
          <%= link_to 'DESTROY', "/blogs/#{@blog.id}", method: :delete %>
        </li>
     </ul>
    <% end %>  
    <%= simple_format(@blog.text) %>
    <span class="name-show">
      <a href="/users/<%= @blog.user.id %>">
        <span>投稿者   </span><%= @blog.user.nickname %>
      </a>
    </span>
  </div>
  <div class="container">
<div class="tweet-container">
  <% if current_user %>
  <%= form_tag("/blogs/#{@blog.id}/comments",method: :post) do %>
   <div class="tweet-comment">
  <textarea name="text" placeholder="COMMENT" rows="2" cols="30"></textarea>
  <input type="submit" value="SENT">
  </div>
  <% end %>
  <% end %>
  <div class="comments">   
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
</div>
</div>
</div>

app/views/blogs/update.html.erb
<div class="body" >
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
     <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header>
     <h1><a class="title"  href="/" >Blog</a></h1>
     <% if user_signed_in? %>
            <div class="top-menu">
            <ul>
              <li> <a  href="/users/<%= current_user.id %>">My page</a>  </li>
               <li> <%= link_to "SignOut", destroy_user_session_path, method: :delete %></li>
            <li><a href="/blogs/new">New</a></li>
            </ul>
            </div>
        <% else %>
        <div class="top">
        <ul>
           <li> <%= link_to "SignIn", new_user_session_path %></li>
            <li><%= link_to "NewRegister", new_user_registration_path %></li>
        </ul>
        </div>
        <% end %>
     </header>
    <%= yield %>
    
     <footer>
      <p>
        Copyright Blog 2019.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="body">
<div class="body-content-abc">
  
  <div class="name"><%= @nickname %>さんの投稿一覧</div>
  <% @blogs.each do |blog| %>
    <div class="body-content" style="background-image: url(<%= blog.image %>);">
      <div class="tweet"><%= simple_format(blog.text) %></div>
    </div>
  <% end %>
</div>
</div>